### ISSUE TITLE
Idempotance logout

### ISSUE THREAD

**Issue by Demetri0** [dergunovs/nuxt-fastify#2]
https://github.com/dergunovs/nuxt-fastify/blob/2a9a424bf5f43fb326a1b0758f4c04aa75187a29/server/routes/api/auth/index.js#L24

Я искренне убеждён, что метод `/logout` должен быть идемотентным, так как сколько бы раз он не вызывался, он приводит к единому результату на сервере - уничтожению сессии пользователя, и при этом не важно сущестовала ли она до этого, т.к. в конечном итоге результат - её отсутствие.

Следовательно, предлогаю сделать его `PUT` или `DELETE` и не возвращать `500`, так будто бы на сервере произошла ошибка (На самом деле даже в текущем варианте это не совсем корректно, т.к. ошибка связана с клиентом который пытается вызывать logout будучи не авторизованным).

**Comment by dergunovs** [comment]
Готово.

https://github.com/dergunovs/nuxt-fastify/commit/175eebe93798517ed6a3a4a7589111571e2ccb35
